#!/bin/bash
# $Id: letsencrypt-renew,v 1.3 2021/02/03 10:52:37 fulford Exp fulford $
# $Source: /src/admin/usr/local/etc/RCS/letsencrypt-renew,v $
# $Revision: 1.3 $
# Author C W Fulford.
# Copyright 2019 (c) C W Fulford.
# Licensed for public use under the LGPL, .
# For assistance contact fulford@fulford.net 0793 572 8612
########################################################################
#cmd=`basename $0`
#ver=`echo "$Id: letsencrypt-renew,v 1.3 2021/02/03 10:52:37 fulford Exp fulford $"|awk '{print $3,$4,$5}'`
#syntax="$cmd [-c <configfile>] [-d] [-h <hostid>] [-v]|-V"
#while [ $# -gt 0 ] ;do
#	case $1 in 
#		-c) config=$2;shift 2;;
#		-d) set -x;debug=0;shift;;
#		-h) hostid=$2;shift 2;;			
#		-v) verbose=:;shift;;
#		-V) echo "$cmd $Revision: 1.3 $ $Date: 2021/02/03 10:52:37 $"|awk '{print $1,$3,$6}';exit;;  
#	esac
#done

#config=${config:-/usr/local/etc/${cmd}.cf
#[ -r $config ]||{echo $cmd: Can't find $config;exit 1}
#eval `sed <$config -ne "/^$hostid:/,/^$/{/^[\t ]*[^#].*/p}"`

imAPath=/etc/letsencrypt/archive/imap.fulford.net
imLPath=/etc/letsencrypt/live/imap.fulford.net
imHost=imap.fulford.net
relink () {
	cd $imAPath
/usr/sbin/apachectl stop
sleep 1
/usr/bin/certbot renew 
/usr/sbin/apachectl start
rsync -va $imAPath/ txslkmail:$imAPath
rsync -va $imLPath/ txslkmail:$imLPath

 
